### PR TITLE
fixed color-category mapping

### PR DESCRIPTION
**Pull request by jringenberg**
This fixes which colors map to which categories!
image

### CODE REVIEW

**Comment by jringenberg** [comment]
@adamgobes This fixes the XP display by reassigning hex values to class names, so the category class name on the counter element will work correctly, same as before.

**Comment by adamgobes** [comment]
@jringenberg awesome, implemented on my branch

**Comment by jringenberg** [comment]
Thanks @adamgobes! What's good practice now that you've implemented this on your branch - should I merge it? Or just delete it?

**Comment by adamgobes** [comment]
@jringenberg yup i think good to merge so that we have source of truth up to date!

**Pull request merged**
